---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: broadinstitute/puppet-pdsh
  description: Puppet module to control the pdsh application
  name: puppet-pdsh
  tags:
    - bits
    - bits-tools
    - pdsh
    - puppet
  title: puppet-pdsh
spec:
  domain: infrastructure-tools
  lifecycle: production
  owner: bits-aviso
  system: puppet
  type: service
